version: "3.7"
services:
  userino-server:
    container_name: userino-server
    build: .
#    network_mode: "host"
    ports:
      - 4001:4001
    environment:
      REDIS_HOST: redis://host.docker.internal:6379
      KAFKA_HOSTS: kafka:9092
      PG: postgresql://postgres:postgres@host.docker.internal:5432/auth
    networks:
      - app-services
#    depends_on:
#      - kafka


networks:
  app-services:
    name: app-services
    external: true
