version: '3.7'

services:
  postgres:
    container_name: postgres_sandbox
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    image: redis:5
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
